### Default configuration, these properties should be set with environment variables in docker/Kubernetes.
APP_CONFIG_DIR: classpath:/shared
APP_LOGGING_DIR: /microservices-demo
SERVICE_REGISTRY_URL: http://service-registry:8761/eureka/
RABBITMQ_SERVICE_HOST: rabbitmq
RABBITMQ_SERVICE_PORT: 5672
RABBITMQ_SERVICE_USERNAME: admin
RABBITMQ_SERVICE_PASSWORD: amqp

logging:
  file: ${APP_LOGGING_DIR}/${spring.application.name}.log
  level:
    demo: DEBUG

spring:
  rabbitmq:
    host: ${RABBITMQ_SERVICE_HOST}
    port: ${RABBITMQ_SERVICE_PORT}
    username: ${RABBITMQ_SERVICE_USERNAME}
    password: ${RABBITMQ_SERVICE_PASSWORD}
  cloud:
    config:
      server:
        native:
          search-locations: file:${APP_CONFIG_DIR}
        # To override downstream services configuration
        overrides:
          APP_LOGGING_DIR: ${APP_LOGGING_DIR}
          SERVICE_REGISTRY_URL: ${SERVICE_REGISTRY_URL}
          spring.rabbitmq.host: ${RABBITMQ_SERVICE_HOST}
          spring.rabbitmq.port: ${RABBITMQ_SERVICE_PORT}
          spring.rabbitmq.username: ${RABBITMQ_SERVICE_USERNAME}
          spring.rabbitmq.password: ${RABBITMQ_SERVICE_PASSWORD}
  profiles:
    # Using local filesystem for demo
    active: native